FROM debian:bookworm

# Install the required packages
RUN apt-get update && apt-get install -y \
    gdal-bin \
    postgresql-client-15 \
    python3-psycopg2 \
    python3-yaml \
    python3-requests \
    git \
    wget \
    make cmake g++ libboost-dev \
    libexpat1-dev zlib1g-dev libpotrace-dev \
    libopencv-dev libbz2-dev libpq-dev libproj-dev lua5.3 liblua5.3-dev \
    pandoc nlohmann-json3-dev pyosmium \
    && rm -rf /var/lib/apt/lists/*

# Install osm2pgsql
WORKDIR /src
RUN wget https://github.com/osm2pgsql-dev/osm2pgsql/archive/refs/tags/2.0.1.tar.gz
RUN tar -xvzf 2.0.1.tar.gz
WORKDIR /src/osm2pgsql-2.0.1
RUN mkdir build
WORKDIR /src/osm2pgsql-2.0.1/build
RUN cmake ..
RUN make -j $(nproc)
RUN make install

# Clone the openstreetmap-carto repository
WORKDIR /src
RUN git clone https://github.com/gravitystorm/openstreetmap-carto.git

# Entry point
WORKDIR /app
COPY import.sh .
RUN chmod +x import.sh
ENTRYPOINT ["/app/import.sh"]